-- Run this script connected to the asistia_back database.
-- Example:
--   psql -U postgres -d asistia_back -f sql/01_create_schema.sql
--
-- This script recreates the schema from zero. It drops the daemon tables first.

BEGIN;

DROP VIEW IF EXISTS v_email_processing_history;

DROP TABLE IF EXISTS app_logs CASCADE;
DROP TABLE IF EXISTS ai_interactions CASCADE;
DROP TABLE IF EXISTS email_processing_attempts CASCADE;
DROP TABLE IF EXISTS mail_messages CASCADE;
DROP TABLE IF EXISTS daemon_runs CASCADE;
DROP TABLE IF EXISTS prompt CASCADE;
DROP TABLE IF EXISTS companies CASCADE;

DROP FUNCTION IF EXISTS set_updated_at();

CREATE TABLE companies (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,

  ms_tenant_id UUID NOT NULL,
  ms_client_id UUID NOT NULL,
  ms_client_secret TEXT NOT NULL,
  ms_mailbox TEXT NOT NULL,
  ms_mail_folder TEXT NOT NULL DEFAULT 'inbox',

  gemini_model TEXT NOT NULL DEFAULT 'gemini-3-flash-preview',

  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT companies_name_not_blank CHECK (btrim(name) <> ''),
  CONSTRAINT companies_mailbox_not_blank CHECK (btrim(ms_mailbox) <> '')
);

COMMENT ON TABLE companies IS
  'Empresas que el daemon monitorea. Cada empresa tiene su propia conexion Microsoft Graph.';
COMMENT ON COLUMN companies.ms_client_secret IS
  'Se guarda para que el daemon pueda conectarse a Graph. En produccion conviene cifrarlo o usar un secrets manager.';

CREATE TABLE prompt (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL UNIQUE REFERENCES companies(id) ON DELETE CASCADE,

  system_instruction TEXT NOT NULL,
  prompt_template TEXT NOT NULL,

  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT prompt_system_instruction_not_blank CHECK (btrim(system_instruction) <> ''),
  CONSTRAINT prompt_template_not_blank CHECK (btrim(prompt_template) <> '')
);

COMMENT ON TABLE prompt IS
  'Prompt usado por Gemini. Hay un solo prompt por empresa.';
COMMENT ON COLUMN prompt.prompt_template IS
  'Template con placeholders: {{company_name}}, {{mailbox}}, {{thread_subject}}, {{conversation_id}}, {{thread_messages}}, {{requester_email}}, {{message_order}}, {{model}}.';

CREATE TABLE daemon_runs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'running' CHECK (
    status IN ('running', 'success', 'partial_error', 'error', 'cancelled')
  ),

  started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  finished_at TIMESTAMPTZ,
  duration_ms INTEGER CHECK (duration_ms IS NULL OR duration_ms >= 0),

  max_emails_configured INTEGER NOT NULL CHECK (max_emails_configured > 0),
  emails_loaded INTEGER NOT NULL DEFAULT 0 CHECK (emails_loaded >= 0),
  emails_processed INTEGER NOT NULL DEFAULT 0 CHECK (emails_processed >= 0),
  success_count INTEGER NOT NULL DEFAULT 0 CHECK (success_count >= 0),
  error_count INTEGER NOT NULL DEFAULT 0 CHECK (error_count >= 0),

  error_message TEXT,
  error_stack TEXT,

  CONSTRAINT daemon_runs_finished_after_started CHECK (
    finished_at IS NULL OR finished_at >= started_at
  )
);

COMMENT ON TABLE daemon_runs IS
  'Un ciclo del daemon para una empresa.';

CREATE TABLE mail_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,

  graph_message_id TEXT NOT NULL,
  conversation_id TEXT,
  mailbox TEXT NOT NULL,
  mail_folder TEXT NOT NULL DEFAULT 'inbox',

  subject TEXT,
  from_name TEXT,
  from_address TEXT,
  received_at TIMESTAMPTZ,
  is_read_at_fetch BOOLEAN,
  body_preview TEXT,

  first_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  seen_count INTEGER NOT NULL DEFAULT 1 CHECK (seen_count > 0),

  CONSTRAINT mail_messages_graph_id_not_blank CHECK (btrim(graph_message_id) <> ''),
  CONSTRAINT mail_messages_company_graph_unique UNIQUE (company_id, graph_message_id)
);

COMMENT ON TABLE mail_messages IS
  'Correos detectados desde Graph. graph_message_id y conversation_id sirven para buscar el correo despues.';

CREATE TABLE email_processing_attempts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  run_id BIGINT NOT NULL REFERENCES daemon_runs(id) ON DELETE CASCADE,
  mail_message_id BIGINT NOT NULL REFERENCES mail_messages(id) ON DELETE CASCADE,

  status TEXT NOT NULL DEFAULT 'processing' CHECK (
    status IN ('processing', 'success', 'error', 'skipped')
  ),
  started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  finished_at TIMESTAMPTZ,
  duration_ms INTEGER CHECK (duration_ms IS NULL OR duration_ms >= 0),

  requires_ticket BOOLEAN,
  decision_json JSONB,

  error_message TEXT,
  error_stack TEXT,

  CONSTRAINT email_processing_finished_after_started CHECK (
    finished_at IS NULL OR finished_at >= started_at
  )
);

COMMENT ON TABLE email_processing_attempts IS
  'Intentos de procesar un correo. En fase test puede haber varios intentos del mismo mensaje porque no se marca como leido.';

CREATE TABLE ai_interactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  run_id BIGINT NOT NULL REFERENCES daemon_runs(id) ON DELETE CASCADE,
  email_processing_attempt_id BIGINT NOT NULL REFERENCES email_processing_attempts(id) ON DELETE CASCADE,
  mail_message_id BIGINT NOT NULL REFERENCES mail_messages(id) ON DELETE CASCADE,
  prompt_id BIGINT NOT NULL REFERENCES prompt(id),

  model TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (
    status IN ('pending', 'success', 'error')
  ),

  system_instruction TEXT NOT NULL,
  prompt_text TEXT NOT NULL,
  prompt_summary TEXT,
  response_text TEXT,
  parsed_decision_json JSONB,

  started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  finished_at TIMESTAMPTZ,
  duration_ms INTEGER CHECK (duration_ms IS NULL OR duration_ms >= 0),
  error_message TEXT,
  error_stack TEXT,

  CONSTRAINT ai_interactions_finished_after_started CHECK (
    finished_at IS NULL OR finished_at >= started_at
  )
);

COMMENT ON TABLE ai_interactions IS
  'Auditoria de IA: prompt enviado, respuesta cruda y decision parseada.';
COMMENT ON COLUMN ai_interactions.prompt_text IS
  'Prompt completo enviado a Gemini. Puede contener datos personales y cuerpo del correo.';
COMMENT ON COLUMN ai_interactions.system_instruction IS
  'Instruccion de sistema enviada a Gemini junto con el prompt.';

CREATE TABLE app_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  run_id BIGINT REFERENCES daemon_runs(id) ON DELETE SET NULL,
  mail_message_id BIGINT REFERENCES mail_messages(id) ON DELETE SET NULL,
  email_processing_attempt_id BIGINT REFERENCES email_processing_attempts(id) ON DELETE SET NULL,
  ai_interaction_id BIGINT REFERENCES ai_interactions(id) ON DELETE SET NULL,

  level TEXT NOT NULL CHECK (level IN ('debug', 'info', 'warn', 'error', 'success')),
  component TEXT NOT NULL,
  event TEXT NOT NULL,
  message TEXT NOT NULL,
  details JSONB NOT NULL DEFAULT '{}'::jsonb,
  error_message TEXT,
  error_stack TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT app_logs_component_not_blank CHECK (btrim(component) <> ''),
  CONSTRAINT app_logs_event_not_blank CHECK (btrim(event) <> ''),
  CONSTRAINT app_logs_message_not_blank CHECK (btrim(message) <> '')
);

COMMENT ON TABLE app_logs IS
  'Logs estructurados por empresa.';

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_companies_set_updated_at
BEFORE UPDATE ON companies
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_prompt_set_updated_at
BEFORE UPDATE ON prompt
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE INDEX idx_companies_active ON companies (is_active);
CREATE INDEX idx_companies_mailbox ON companies (lower(ms_mailbox));

CREATE INDEX idx_daemon_runs_company_started ON daemon_runs (company_id, started_at DESC);
CREATE INDEX idx_daemon_runs_company_status ON daemon_runs (company_id, status, started_at DESC);

CREATE INDEX idx_mail_messages_company_conversation ON mail_messages (company_id, conversation_id);
CREATE INDEX idx_mail_messages_company_received ON mail_messages (company_id, received_at DESC);
CREATE INDEX idx_mail_messages_from_address ON mail_messages (company_id, lower(from_address));

CREATE INDEX idx_email_attempts_run ON email_processing_attempts (run_id, started_at DESC);
CREATE INDEX idx_email_attempts_company_status ON email_processing_attempts (company_id, status, started_at DESC);
CREATE INDEX idx_email_attempts_message ON email_processing_attempts (mail_message_id, started_at DESC);

CREATE INDEX idx_ai_interactions_company_started ON ai_interactions (company_id, started_at DESC);
CREATE INDEX idx_ai_interactions_message ON ai_interactions (mail_message_id, started_at DESC);
CREATE INDEX idx_ai_interactions_prompt ON ai_interactions (prompt_id, started_at DESC);
CREATE INDEX idx_ai_interactions_status ON ai_interactions (company_id, status, started_at DESC);
CREATE INDEX idx_ai_interactions_decision_gin ON ai_interactions USING gin (parsed_decision_json);

CREATE INDEX idx_app_logs_company_created ON app_logs (company_id, created_at DESC);
CREATE INDEX idx_app_logs_company_level ON app_logs (company_id, level, created_at DESC);
CREATE INDEX idx_app_logs_run ON app_logs (run_id, created_at DESC);
CREATE INDEX idx_app_logs_message ON app_logs (mail_message_id, created_at DESC);
CREATE INDEX idx_app_logs_details_gin ON app_logs USING gin (details);

CREATE OR REPLACE VIEW v_email_processing_history AS
SELECT
  c.id AS company_id,
  c.name AS company_name,
  r.id AS run_id,
  r.started_at AS run_started_at,
  m.id AS mail_message_id,
  m.graph_message_id,
  m.conversation_id,
  m.subject,
  m.from_address,
  m.received_at,
  a.id AS attempt_id,
  a.status AS processing_status,
  a.requires_ticket,
  a.decision_json,
  ai.id AS ai_interaction_id,
  ai.model AS ai_model,
  ai.status AS ai_status,
  p.id AS prompt_id,
  ai.parsed_decision_json,
  a.error_message AS processing_error,
  ai.error_message AS ai_error
FROM email_processing_attempts a
JOIN companies c ON c.id = a.company_id
JOIN daemon_runs r ON r.id = a.run_id
JOIN mail_messages m ON m.id = a.mail_message_id
LEFT JOIN ai_interactions ai ON ai.email_processing_attempt_id = a.id
LEFT JOIN prompt p ON p.id = ai.prompt_id;

COMMIT;
